"""
mcp_server.py — Dhan Algo Read-Only AI Gateway (FastMCP)
=========================================================
AI agents connect here to READ system state.
NO tool here can modify state, place orders, or override RiskManager.
"""

import json
from mcp.server.fastmcp import FastMCP
from app.core.redis import redis_client

mcp = FastMCP("Dhan Algo Gateway")


@mcp.tool()
async def get_market_status() -> str:
    """Get current market snapshot: SENSEX, LTPs, open positions, PnL, kill switch status."""
    try:
        snapshot = await redis_client.get("market_snapshot")
        if snapshot:
            data = json.loads(snapshot)
            return (
                f"SENSEX: {data.get('sensex', 'N/A')} | "
                f"CE LTP: {data.get('ce_ltp', 'N/A')} | "
                f"PE LTP: {data.get('pe_ltp', 'N/A')} | "
                f"Open Positions: {data.get('open_positions', 0)} | "
                f"Kill Switch: {'ACTIVE' if data.get('kill_switch') else 'Off'} | "
                f"Last Updated: {data.get('timestamp', 'unknown')}"
            )
        return "No market data available yet. Worker may be starting or market is closed."
    except Exception as e:
        return f"Error reading market status: {e}"


@mcp.tool()
async def get_positions() -> str:
    """Get all currently open trading positions with P&L, entry price, and stop loss levels."""
    try:
        snapshot = await redis_client.get("market_snapshot")
        if not snapshot:
            return "No position data available."
        data = json.loads(snapshot)
        positions = data.get("positions", [])
        if not positions:
            return "No open positions."
        lines = []
        for p in positions:
            lines.append(
                f"{p['symbol']} [{p['option_type']}] | "
                f"Qty: {p['quantity']} | "
                f"Entry: ₹{p['entry_price']:.2f} | "
                f"LTP: ₹{p['current_price']:.2f} | "
                f"SL: ₹{p['stop_loss']:.2f} | "
                f"Unrealized PnL: ₹{p['unrealized_pnl']:.2f} | "
                f"Trailed: {'Yes' if p.get('trailed_sl') else 'No'}"
            )
        return "\n".join(lines)
    except Exception as e:
        return f"Error reading positions: {e}"


@mcp.tool()
async def get_pnl() -> str:
    """Get current session P&L: realized, unrealized, trades executed, and win rate."""
    try:
        snapshot = await redis_client.get("market_snapshot")
        if not snapshot:
            return "No PnL data available."
        data = json.loads(snapshot)
        realized = data.get("daily_pnl", 0)
        trades = data.get("trades_today", 0)
        open_pos = data.get("open_positions", 0)
        return (
            f"Realized P&L: ₹{realized:.2f} | "
            f"Trades Today: {trades} | "
            f"Open Positions: {open_pos}"
        )
    except Exception as e:
        return f"Error reading PnL: {e}"


@mcp.tool()
async def get_last_signal() -> str:
    """Get the most recent trading signal generated by the strategy."""
    try:
        signal = await redis_client.get("last_signal")
        if not signal:
            return "No signal generated yet this session."
        data = json.loads(signal)
        return (
            f"Symbol: {data.get('symbol')} | "
            f"Direction: {data.get('direction')} | "
            f"Entry: ₹{data.get('entry', 'N/A')} | "
            f"SL: ₹{data.get('sl', 'N/A')} | "
            f"Reason: {data.get('reason', '')} | "
            f"Time: {data.get('timestamp', '')}"
        )
    except Exception as e:
        return f"Error reading last signal: {e}"


if __name__ == "__main__":
    mcp.run(transport="stdio")
